#!/bin/bash

set -eu

rm -f .bash.pid

rm -f stdin stdout stderr
mkfifo stdin 
touch stdout stderr

exec 10<>stdin
exec 11<>stdout
exec 12<>stderr

nohup bash -i -s <&10 >&11 2>&12 & 
BASH_PID=$! 
echo $BASH_PID > .bash.pid
echo "info: bash launched. (pid: $BASH_PID)"
