#!/bin/bash

set -eu

source $(dirname $(realpath ${BASH_SOURCE[0]}))/tmox-header

if [[ -f $SPID_PATH ]] && ps -p $(cat $SPID_PATH) >/dev/null 2>&1; then
  echo "$0: error: bash already launched."
  exit
fi

mkdir -p $TMOX_ROOT
rm -rf $TMOX_ROOT/*

mkfifo $STDIN_PATH
touch $STDOUT_PATH $STDERR_PATH

exec 10<>$STDIN_PATH
exec 11<>$STDOUT_PATH
exec 12<>$STDERR_PATH

# TODO: resize row/col when the terminal changes.
# For now, it's the initial dimension.
NUM_ROWS_ORG=$(stty size | cut -d' ' -f1)
NUM_COLS_ORG=$(stty size | cut -d' ' -f2)

nohup script --return --quiet \
  -c 'bash --rcfile <(cat ~/.bashrc; \
      echo '"'"'PS1="${PS1:-}[tmox] "'"'"';
      stty rows '"$NUM_ROWS_ORG"' cols '"$NUM_COLS_ORG"') -i -s' \
  /dev/null <&10 >&11 2>&12 & 
BASH_PID=$! 
echo $BASH_PID > $SPID_PATH 
echo "info: bash launched. (pid: $BASH_PID)"
