#!/bin/bash

set -eu

source $(dirname $(realpath ${BASH_SOURCE[0]}))/tmox-header

ATTACH_PID=$$
TARGET_BASH_PID=$(cat $SPID_PATH)

if [[ -z "$TARGET_BASH_PID" ]]; then
  echo "$0: error: background bash not found."
  exit
fi

if ! ps -p $TARGET_BASH_PID >/dev/null 2>&1; then
  echo "$0: error: bash not exists."
  exit
fi

echo "$0: attaching..."

exec 10<>$STDIN_PATH
exec 11<>$STDOUT_PATH
exec 12<>$STDERR_PATH

(
  trap 'kill 0' EXIT

  tail --pid $TARGET_BASH_PID -f $STDOUT_PATH &
  STDOUT_PID=$!
  tail --pid $TARGET_BASH_PID -f $STDERR_PATH >&2 &
  STDERR_PID=$!

  wait $STDOUT_PID
  kill -SIGINT $ATTACH_PID 
) &
PRINTER_PID=$!

trap 'kill $PRINTER_PID' EXIT
trap 'echo; echo "$0: detaching..."; exit' SIGINT

while IFS= read -srn1 prompt; do
  if [[ $prompt == "" ]]; then
    echo >&10
  else
    printf "$prompt" >&10
  fi
done
