#!/bin/bash

set -eu

rm -f .bash.pid

rm -f stdin stdout stderr
mkfifo stdin
touch stdout stderr

exec 10<>stdin
exec 11<>stdout
exec 12<>stderr

nohup script --return --quiet \
  -c 'bash --rcfile <(cat ~/.bashrc; echo '"'"'PS1="${PS1:-}[tmox] "'"'"') -i -s' \
  /dev/null <&10 >&11 2>&12 & 
SCRIPT_PID=$! 
echo $SCRIPT_PID > .bash.pid
echo "info: bash launched. (pid: $SCRIPT_PID)"
