#!/bin/bash

set -eu

CUR_TTY=$(tty)
ATTACH_PID=$$
TARGET_BASH_PID=$(cat .bash.pid)

if [[ -z "$TARGET_BASH_PID" ]]; then
  echo "error: background bash not found."
  exit
fi

if ! ps -p $TARGET_BASH_PID >/dev/null 2>&1; then
  echo "error: bash not exists."
  exit
fi

echo "$0: attaching..."

exec 10<>stdin
exec 11<>stdout
exec 12<>stderr

tail --pid $TARGET_BASH_PID -f stdout &
STDOUT_PID=$!
tail --pid $TARGET_BASH_PID -f stderr >&2 &
STDERR_PID=$!

wait $STDOUT_PID
kill -SIGINT $ATTACH_PID 

trap 'kill -9 $STDOUT_PID $STDERR_PID' EXIT
trap 'echo; echo "$0: detaching..."; exit' SIGINT

while IFS= read -srn1 prompt; do
  if [[ $prompt == "" ]]; then
    echo >&10
  else
    printf "$prompt" >&10
  fi
done
